accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,thankyou,sorry,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,StudentReportView,StudentEssayView,index_page,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,ActiveSessionSubmitView,home,entername,index,ActiveSessionView,QuestionSubmitView
)
from django.conf.urls import url
app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),
    url(r'^/$', index_page, name='indexpage'),
    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    url(r'^enter-details/$', entername, name='entername'),
    url(r'^home/$', home, name='home'),
    url(r'index',index,name='index'),
    url(r'thankyou',thankyou,name='thankyou'),
    url(r'sorry', sorry, name='sorry'),
    path('student-report/',StudentReportView.as_view(),name = "student_report"),
    path('student-report/(?P<pk>[0-9]+)/$',StudentEssayView.as_view(),name="student_essay"),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),
    path('active-session/', ActiveSessionView.as_view(), name='active_session'),
    path('active-session-done/', ActiveSessionSubmitView.as_view(), name='activesessionsubmit'),
    path('question-submit/', QuestionSubmitView.as_view(), name='questionsubmit'),
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url

from django.shortcuts import render_to_response
from django.template import RequestContext
def handler404(request, *args, **argv):
    response = render_to_response('accounts/error.html', {})
    response.status_code = 404
    return response
def handler500(request, *args, **argv):
    response = render_to_response('accounts/thankyou.html', {})
    response.status_code = 500
    return response

app_name = 'main'
from main.views import IndexPageView,ChangeLanguageView,LandingPageView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', IndexPageView.as_view(), name='index'),
    path('',LandingPageView.as_view(),name = 'landing_page'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.views.generic import TemplateView
from accounts.models import *
#from urllib import request


class IndexPageView(TemplateView):
    template_name = 'main/index.html'
    def get_context_data(self, *args, **kwargs):
        context = super(IndexPageView, self).get_context_data(*args, **kwargs)
        context['name'] = 'Gryffindor'

        try:
            account_list = EssayApproval.objects.filter(user=self.request.user)
            print(account_list)
            context['essay'] = EssayApproval.objects.filter(user=self.request.user)
        except:
            pass
        return context

class ChangeLanguageView(TemplateView):
    template_name = 'main/change_language.html'

class LandingPageView(TemplateView):
    template_name = 'main/landingpage.html'

content/templates/main/change_language.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% get_current_language as language_code %}
    {% get_available_languages as languages %}

    <h4>{% trans 'Change language' %}</h4>

    <form action="{% url 'set_language' %}" method="post">

        {% csrf_token %}

        <input name="next" type="hidden" value="{{ redirect_to }}"/>

        <div class="form-group">
            <label class="form-control-label" for="language-field">{% trans 'Select the language' %}</label>
            <select name="language" class="form-control" id="language-field">
                {% for code, name in languages %}
                    <option value="{{ code }}" {% if code == language_code %} selected="selected"{% endif %}>
                        {{ name }} ({{ code }})
                    </option>
                {% endfor %}
            </select>
        </div>

        <button class="btn btn-success">{% trans 'Change' %}</button>

    </form>

{% endblock %}

content/templates/main/index.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% if request.user.is_authenticated %}

        {% trans 'Welcome ' %} <b>{{ request.user.username }}</b>.

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

content/templates/main/landingpage.html
{% load staticfiles %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Aditya Raj">
    <!-- Page Title -->
    <title>Write Essay &mdash;</title>
    <meta name="description" content="Welcome to LNCT essay writing portal. You can write essay assignements here which will be directly submitted to the concerned faculty.">
    <meta name="keywords" content="lnct,essay,article,faculty,bhopal,lakshmi narain college,college">
    <!--CSS  Tags-->
    <script src="http://code.jquery.com/jquery-1.5.js"></script>

    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'css/shortcodes.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/skins/default-skin.css' %}">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'images/logos/favicon.png' %}">
</head>

<body>
    <!-- Preloader -->
    <div class="preloader">
        <!-- Preloader Color & Opction -->
        <div class="loader-4">
            <div class="loader">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
    </div>
    <!-- Preloader -->

	    <header class="header header-sticky header-transparent-dark">
        <!-- Start Top Search -->
        <div class="top-search">
            <span class="input-group-addon close-search">
                <i class="ti-close"></i>
            </span>
            <div class="top-search-page">
                <div class="input-group absolute-center">
                    <span class="input-group-addon search-icon">
                        <i class="ti-search"></i>
                    </span>
                    <input type="text" class="form-control search-input" placeholder="Search anything ....">
                </div>
            </div>
        </div>
        <!-- End Top Search -->
        <!-- Static navbar -->
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'landing_page' %}">
                    <img src="{% static 'images/logos/logo-light.png' %}" alt="notfound">
                </a>
                <ul class="extra-navbar-item">

                </ul>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span> </span>
                    <span> </span>
                    <span> </span>
                </button>
                <!-- Nav Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="%24.html" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Blog
                            </a>
                            <ul class="dropdown-menu to-left">
                                <li>
                                    <a class="dropdown-item dropdown-toggle" href="#">Blog Masonry</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="blog-masonry-columns-4.html">Grid 4</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="dropdown-item dropdown-toggle" href="#">Single Post</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="blog-single-left.html">Left Sidebar</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Teacher Login</a>
                        </li>

                    </ul>
                </div>
                <!-- End Nav Items -->
            </div>
        </nav>
    </header>
    <!-- end header -->
    <section class="overlay parallax" data-speed="0.1" data-background="{% static 'images/lnct.jpeg' %}" data-overlay-color="dark"
        data-overlay="6">
        <div class="container">
            <div class="row align-items-center full-height text-white  p-y100">
                <div class="col-lg-8 mx-auto col-12 text-center">
                    <h2 class="p-b20 f-size-60 l-height-60 f-w-300 l-spacing-4">Welcome to LNCT</h2>
                    <h5 class="text-uppercase p-b0 l-spacing-5">Essay and article writing portal</h5>
                    <h6 class="p-b20 l-spacing-2 f-w-300"></h6>
                    <a href="{% url 'accounts:index' %}" class="button button-glass button-circle">Start Writing</a>
                </div>
                <a href="#about" class="m-t100 d-block page-scroll">
                    <div class="mouse-wrapper">
                        <div class="mouse">
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </section>
    <section id="about" class="section-padding">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 p-sm-b40">
                    <div class="section-title">
                        <h2 class="f-w-700">Writing improvements</h2>
                        <div class="title-divider"></div>
                    </div>
                    <p class="text1 m-t10">The benefit that comes with writing essays or articles is the ability to establish yourself, your website, your company profile, etc. Sharing valuable information is a great way for businesses and individuals to help the world get to know them and trust their services or knowledge. In terms of optimizing your visibility on the internet, writing articles and giving reference to you
                        as the source is something that can help people find more accurate information from you and also from the other sources connected to you.
                    </p><p>
                    <ul>
                        <div class="text-uppercase">Tips :</div>
                        <li>
                            &nbsp; Choose interesting angles.
                        </li>
                        <li>
                           &nbsp; Create an outline.
                        </li>
                        <li>
                           &nbsp; Beware of spelling mistakes.
                        </li>
                        <li>
                           &nbsp; All the grammatical mistakes is also recorded.
                        </li>


                </ul></p>
                    <p>All the best.</p>
                </div>
                <div class="col-md-5 offset-md-1 text-right">
                    <img class="rounded shadow" src="{% static 'images/home/writing.png' %}" alt="About">
                </div>
            </div>
        </div>
    </section>



<footer class="footer-padding footer-dark">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-6 col-sm-6">
                        <div class="widget">
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/adityaraj1711">The website is developed by Aditya Raj (CSE)</a>
                                </li>
                            </ul>
                            <div class="footer-social-icons">
                                <ul>

                            <!-- start social media -->

                                    <li>
                                        <a href="https://www.facebook.com/adityaraj1711">
                                            <span class="fa fa-facebook"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com/in/adityamailbox0/">
                                            <span class="fa fa-linkedin"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- end social media -->
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <!-- Footer Navigation -->
                        <div class="widget">
                            <h6 class="text-uppercase">Navigation</h6>
                            <ul>
                                <li>
                                    <a href="{% url 'landing_page' %}">Home</a>
                                </li>
                                <li>
                                    <a href="#">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- Footer Navigation -->
                    </div>

                </div>
            </div>
        </div>
        <!-- Footer Copyright -->
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <!-- Footer Copyright Text -->
                        <p class="copyright-text">Copyright &copy;
                            <a href="">LNCT, Bhopal</a> 2019, All rights reserved.</p>
                        <!-- Footer Copyright Text -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Copyright -->
    </footer>

    <!-- All Javascript -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>