accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,thankyou,sorry,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,StudentReportView,StudentEssayView,index_page,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,ActiveSessionSubmitView,home,entername,index,ActiveSessionView,QuestionSubmitView
)
from django.conf.urls import url
app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),
    url(r'^/$', index_page, name='indexpage'),
    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    url(r'^enter-details/$', entername, name='entername'),
    url(r'^home/$', home, name='home'),
    url(r'index',index,name='index'),
    url(r'thankyou',thankyou,name='thankyou'),
    url(r'sorry', sorry, name='sorry'),
    path('student-report/',StudentReportView.as_view(),name = "student_report"),
    path('student-report/(?P<pk>[0-9]+)/$',StudentEssayView.as_view(),name="student_essay"),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),
    path('active-session/', ActiveSessionView.as_view(), name='active_session'),
    path('active-session-done/', ActiveSessionSubmitView.as_view(), name='activesessionsubmit'),
    path('question-submit/', QuestionSubmitView.as_view(), name='questionsubmit'),
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url

from django.shortcuts import render_to_response
from django.template import RequestContext
def handler404(request, *args, **argv):
    response = render_to_response('accounts/error.html', {})
    response.status_code = 404
    return response
def handler500(request, *args, **argv):
    response = render_to_response('accounts/thankyou.html', {})
    response.status_code = 500
    return response

app_name = 'main'
from main.views import IndexPageView,ChangeLanguageView,LandingPageView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', IndexPageView.as_view(), name='index'),
    path('',LandingPageView.as_view(),name = 'landing_page'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone

class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)


class Teacher(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    type = models.CharField(default="T",max_length=2)
    is_active = models.BooleanField(default=False)
    temp_password = models.CharField(default="",max_length=5)
    question = models.CharField(default="",max_length=200)
    def __str__(self):
        return self.user.username

class Section(models.Model):
    semester = models.IntegerField(default=0)
    section = models.CharField(default="",max_length=20)
    branch = models.CharField(default="",max_length=20)
    academic_year = models.CharField(default="20XX-20YY",max_length=20)
    def __str__(self):
        return self.section

from django_mysql.models import ListTextField

class Student(models.Model):
    teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE,null=True)
    question = models.CharField(default="",max_length=200)
    section = models.ForeignKey(Section,on_delete=models.CASCADE,null=True)
    essay = models.CharField(default="",max_length=6000)
    enrollment = models.CharField(default="0103CSYYRRRR",max_length=15)
    error_count = models.IntegerField(default=0)
    errors = ListTextField(
        base_field=models.CharField(max_length=100),
        size=100,
        max_length=(1000 * 1001)
    )
    corrected_essay = models.CharField(default="",max_length=6000)
    name = models.CharField(default="",max_length=50)
    marks = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,ChangeSessionForm,WriteEssayForm,QuestionForm
)
from .models import Activation


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)

class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up!'))

        return redirect('index')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('accounts:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk)).decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')

class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully changed your email!'))

        return redirect('accounts:change_email')


class RemindUsernameView(GuestOnlyView, FormView):
    template_name = 'accounts/remind_username.html'
    form_class = RemindUsernameForm

    def form_valid(self, form):
        user = form.user_cache
        send_forgotten_username_email(user.email, user.username)

        messages.success(self.request, _('Your username has been successfully sent to your email.'))

        return redirect('accounts:remind_username')


class ChangePasswordView(BasePasswordChangeView):
    template_name = 'accounts/profile/change_password.html'

    def form_valid(self, form):
        # Change the password
        user = form.save()

        # Re-authentication
        login(self.request, user)

        messages.success(self.request, _('Your password was changed.'))

        return redirect('accounts:change_password')

accounts/templates/accounts/activesession.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}
<title>Activate session</title>

{% block content %}

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="form-actions">
      <button type="submit">Send</button>
    </div>
    </form>


{% endblock %}

accounts/templates/accounts/activesessionsubmit.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

Recorded

{% endblock %}

accounts/templates/accounts/entername.html
{% load staticfiles %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Deep Saha">
    <!-- Page Title -->
    <title>Write Essay &mdash;</title>
    <!--CSS  Tags-->
    <script src="http://code.jquery.com/jquery-1.5.js"></script>

    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'css/shortcodes.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/skins/default-skin.css' %}">
    <!-- Favicons -->

    <script>
        function validateForm() {
          var x = document.forms["register"]["name"].value;
          if (x == "") {
            alert("Name must be filled out");
            return false;
          }
          if(document.register.enrollment.value.length == 0)
            {
                alert("Please enter the enrollment number");
                return false;
            }
          else{
            if(!validateEnrollment(document.register.enrollment.value)){
                alert("Enter enrollment in the format CCCCBBYYRRRR (Ex- 0103CS161013)");
                return false;
            }

          }

        }
        function validateEnrollment(phone)
        {
            var re = /^([0-9]){4}([a-zA-Z]){2}([0-9]){6}?$/
            return re.test(phone);
        }

    </script>

    <link rel="shortcut icon" href="{% static 'images/logos/favicon.png' %}">
</head>
<body>
    <!-- Preloader -->
    <div class="preloader">
        <!-- Preloader Color & Opction -->
        <div class="loader-4">
            <div class="loader">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
    </div>
    <!-- Preloader -->

	    <header class="header header-sticky header-transparent-dark">
        <!-- Start Top Search -->
        <div class="top-search">
            <span class="input-group-addon close-search">
                <i class="ti-close"></i>
            </span>
            <div class="top-search-page">
                <div class="input-group absolute-center">
                    <span class="input-group-addon search-icon">
                        <i class="ti-search"></i>
                    </span>
                    <input type="text" class="form-control search-input" placeholder="Search anything ....">
                </div>
            </div>
        </div>
        <!-- End Top Search -->
        <!-- Static navbar -->
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="index-2.html">
                    <img src="{% static 'images/logos/logo-light.png' %}" alt="logo">
                </a>
                <ul class="extra-navbar-item">

                </ul>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span> </span>
                    <span> </span>
                    <span> </span>
                </button>
                <!-- Nav Items -->
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'landing_page' %}">Home</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="%24.html" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Blog
                            </a>
                            <ul class="dropdown-menu to-left">
                                <li>
                                    <a class="dropdown-item dropdown-toggle" href="#">Blog Masonry</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="blog-masonry-columns-4.html">Grid 4</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="dropdown-item dropdown-toggle" href="#">Single Post</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="blog-single-left.html">Left Sidebar</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link" href="#">Teacher Login</a>
                        </li>

                    </ul>
                </div>
                <!-- End Nav Items -->
            </div>
        </nav>
    </header>
    <!-- end header -->
    <section class="full-height overlay text-white" data-background="{% static 'images/lnct.jpeg' %}" data-overlay-color="black"
        data-overlay="8">
        <div class="container">
            <div class="row full-height align-items-center p-y100">
                <div class="col-lg-7 p-md-b40">
                    <p class="text f-w-700">Attention !!</p>
                    <h1 class="l-height-50 f-size-40 f-w-700 mb-10">Enter your details</h1>
                    <p class="lead f-w-700 m-b30">You are expected to fill your details correct.<br><br> Warning : <br><li> Wrong submission of details will not be entertained for evaluation.</li>
                    <li> Empty submission of essay will not be marked submitted.</li>
                    </p>
                    <a class="videopopup" href="https://www.youtube.com/watch?v=s9rL5WetfX4">
                        <div class="video-button video-button-light">
                            <i class="fa fa-play">
                            </i>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 offset-lg-1">
                    <form name="register" action="{% url 'accounts:entername' %}" method="post"  onsubmit="return validateForm();" class="form p-y40 p-x20 rounded shadow-lg white-bg">
                                        {% csrf_token %}
                        <div class="form-group">
                            <label class="text-capitalize">Your Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-capitalize">Enrollment</label>
                            <input type="text" name="enrollment" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-capitalize">Teacher</label>
                            <select name="teach" class="form-control">
                                {% for teacher in teachers %}
                                <option value="{{ teacher.id }}"> {{ teacher.user }} </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="text-capitalize">Section</label>
                            <select name="section" class="form-control">
                                {% for section in sections %}
                                <option value="{{ section.id }}"> {{ section.academic_year }} | {{ section.section }} | {{ section.branch }} </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="text-capitalize">Password</label>
                            <input type="Password" name="temp_password" class="form-control">
                        </div>
                        <div class="form-group m-b0 text-center">
                            <input class="button button-color button-lg button-circle f-w-700" type="submit" value="Submit" />
                            <!--<button class="button button-color button-lg button-circle f-w-700">Next</button>-->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

<footer class="footer-padding footer-dark">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-6 col-sm-6">
                        <div class="widget">
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/adityaraj1711">The website is developed by Aditya Raj (CSE)</a>
                                </li>
                            </ul>
                            <div class="footer-social-icons">
                                <ul>

                            <!-- start social media -->

                                    <li>
                                        <a href="https://www.facebook.com/adityaraj1711">
                                            <span class="fa fa-facebook"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com/in/adityamailbox0/">
                                            <span class="fa fa-linkedin"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- end social media -->
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <!-- Footer Navigation -->
                        <div class="widget">
                            <h6 class="text-uppercase">Navigation</h6>
                            <ul>
                                <li>
                                    <a href="{% url 'landing_page' %}">Home</a>
                                </li>
                                <li>
                                    <a href="#">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- Footer Navigation -->
                    </div>

                </div>
            </div>
        </div>
        <!-- Footer Copyright -->
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <!-- Footer Copyright Text -->
                        <p class="copyright-text">Copyright &copy;
                            <a href="">LNCT, Bhopal</a> 2019, All rights reserved.</p>
                        <!-- Footer Copyright Text -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Copyright -->
    </footer>


    <!-- All Javascript -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

accounts/templates/accounts/error.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="aditya">
    <!-- Page Title -->
    <title>Thankyou &mdash;</title>
    <!--CSS  Tags-->
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'css/shortcodes.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/skins/default-skin.css' %}">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'images/logos/favicon.png' %}">
</head>
<body>
    <!-- Preloader -->
    <div class="preloader">
        <div class="loader-4">
            <div class="loader">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
    </div>
    <!-- Preloader -->
    <section class="full-height gray-text">
        <div class="container">
            <div class="row full-height align-items-center">
                <div class="col-sm-4 text-center d-none d-sm-block">
                    <img src="{% static 'images/pages/construction.png' %}" alt="No img">
                </div>
                <div class="col-sm-8">
                    <h1 class="display-4 f-w-700 m-b10">Sorry !!</h1>
                    <h4 class="f-w-700 m-b10 text-uppercase">Error!!.</h4>
                    <h5 class="f-w-700 m-b10 text-uppercase">We will back</h4>
                        <p class="text m-t10 m-b20">
                        	Something phishing is going on or the site is broken. Sorry for the inconvenience.
                        </p>
                </div>
            </div>
        </div>
    </section>



    <!-- All Javascript -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index page</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/log_in.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Log in' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Log in' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:restore_password' %}">{% trans 'Forgot your password?' %}</a>
        </li>
        <li>
            <a href="{% url 'accounts:remind_username' %}">{% trans 'Forgot your username?' %}</a>
        </li>
        <li>
            <a href="{% url 'accounts:resend_activation_code' %}">{% trans 'Resend an activation code' %}</a>
        </li>
    </ul>

{% endblock %}

accounts/templates/accounts/log_out.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

accounts/templates/accounts/restore_password.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}